# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Elixir CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  deploy:

    name: Deploy to gigalixir
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
          with:
            ref: master # Check out master instead of the latest commit
            fetch-depth: 0 # Checkout the whole branch

       # - uses: actions/setup-python@v2
        #  with:
        #    python-version: 3.8.1

        - uses: mhanberg/gigalixir-action@v0.6.2
          with:
            # APP_SUBFOLDER: my-app-subfolder  # Add only if you want to deploy an app that is not at the root of your repository
            GIGALIXIR_APP: stop-info # Feel free to also put this in your secrets
            GIGALIXIR_CLEAN: true # defaults to false
            GIGALIXIR_USERNAME: ${{ secrets.GIGALIXIR_USERNAME }}
            GIGALIXIR_PASSWORD: ${{ secrets.GIGALIXIR_PASSWORD }}
            MIGRATIONS: false  # defaults to true
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
